---
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/instance: test
  name: mosquitto-tcp
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - name: mosquitto-tcp
      nodePort: 31883
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app.kubernetes.io/instance: test
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: mosquitto-ephemeral
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer
  labels:
    app.kubernetes.io/instance: test
  name: mosquitto-tls
spec:
  ports:
    - name: mosquitto-tls
      port: 8883
      protocol: TCP
      targetPort: 8883
  selector:
    app.kubernetes.io/instance: test
