apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: b4mad-racing
  app.kubernetes.io/version: v0.1.0-dev
resources:
  - telegraf/deployment.yaml
  - telegraf/service.yaml
  - telegraf/service_account.yaml
configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf/telegraf.conf
generatorOptions:
  disableNameSuffixHash: true
