apiVersion: v1
data:
  accessKeyID: QUtJQVpSN1pVQTJUUEVNUE9BRks=
  bucketName: czM6Ly9iNG1hZC1yYWNpbmctc21hdWcvaW5mbHV4ZGI=
  region: dXMtZWFzdC0x
  secretAccessKey: bDNZTVBycGQ3WThrOXFuTko3dE55VWZlWHpXV0VSbWhVT2hod2xxcA==
kind: Secret
metadata:
  creationTimestamp: null
  name: b4mad-racing-influxdb-backup
