apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: b4mad-racing-influxdb2
spec:
  endpoints:
    - interval: 15s
      port: http
      scheme: http
      relabelings:
        - sourceLabels: [service]
          regex: "b4mad-racing-influxdb2"
          action: replace
          targetLabel: field
          replacement: telemetry.b4mad.racing
  namespaceSelector:
    matchNames:
      - b4mad-racing
  selector: {}
