version: '3'
services:
  telegraf:
    platform: linux/x86_64
    image: telegraf:1.22-alpine
    env_file: configuration.env
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
    - '8125:8125/udp'

  influxdb:
    platform: linux/x86_64
    container_name: influxdb
    image: influxdb:2.2-alpine
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      # - ./:/imports
      - ./influxdb/data:/var/lib/influxdb2:rw
      # - ./influxdb/config.yml:/etc/influxdb2/config.yml

  grafana:
    platform: linux/x86_64
    image: grafana/grafana:8.5.0
    depends_on:
      - influxdb
    env_file: configuration.env
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  mosquitto:
    platform: linux/x86_64
    container_name: mosquitto
    image: eclipse-mosquitto:2-openssl
    user: "0"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/conf:/mosquitto/config

volumes:
  grafana_data: {}
  influxdb_data: {}
