apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: b4mad-racing-telegraf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test
    spec:
      containers:
        - env:
            - name: HOSTNAME
              value: telegraf
          image: telegraf:1.22-alpine
          name: telegraf
          resources: {}
          volumeMounts:
            - mountPath: /etc/telegraf
              name: config
      restartPolicy: Always
      serviceAccount: b4mad-racing-telegraf
      serviceAccountName: b4mad-racing-telegraf
      volumes:
        - configMap:
            defaultMode: 420
            name: telegraf-config
          name: config
